# Generated by Django 3.2.10 on 2022-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=90, verbose_name='Логин')),
                ('fik', models.CharField(default='0', max_length=200, verbose_name='ФИК(-О)')),
                ('scores', models.IntegerField(default=0, verbose_name='Очки Ls')),
                ('pravil', models.IntegerField(default=0, verbose_name='Прав Отв')),
                ('bezosh', models.IntegerField(default=0, verbose_name='Безош отв')),
                ('scoresl1', models.IntegerField(default=0, verbose_name='Очки L1')),
                ('scoresl2', models.IntegerField(default=0, verbose_name='Очки L2')),
                ('scoresl3', models.IntegerField(default=0, verbose_name='Очки L3')),
                ('scoresl4', models.IntegerField(default=0, verbose_name='Очки L4')),
                ('scoresl5', models.IntegerField(default=0, verbose_name='Очки L5')),
                ('scoresl6', models.IntegerField(default=0, verbose_name='Очки L6')),
                ('scoresl7', models.IntegerField(default=0, verbose_name='Очки L7')),
                ('pop', models.IntegerField(default=1, verbose_name='Попытки')),
                ('poptd', models.IntegerField(default=0, verbose_name='Поп сег')),
                ('res1', models.IntegerField(default=0, verbose_name='РезЦел1')),
                ('res2', models.IntegerField(default=0, verbose_name='РезЦел2')),
                ('scorTD', models.IntegerField(default=0, verbose_name='Очки TD')),
                ('quantwin', models.IntegerField(default=0, verbose_name='Побед дня')),
                ('quanttop', models.IntegerField(default=0, verbose_name='TOPы7 дня')),
                ('pole1', models.CharField(default='0', max_length=200, verbose_name='Поле1')),
                ('pole2', models.CharField(default='0', max_length=200, verbose_name='Поле2')),
            ],
            options={
                'verbose_name': 'Данные участника',
                'verbose_name_plural': 'Данные участника',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Indexs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=90, verbose_name='Указатели')),
                ('ips', models.CharField(default='0', max_length=800, verbose_name='IP Users')),
                ('ipskol', models.CharField(default='0', max_length=200, verbose_name='Quantity IP')),
                ('curdate', models.DateField(default='2022-01-01', verbose_name='Сегодняшняя дата')),
                ('pole1', models.CharField(default='0', max_length=200, verbose_name='Поле1')),
                ('pole2', models.CharField(default='0', max_length=200, verbose_name='Поле2')),
            ],
            options={
                'verbose_name': 'Индексы и указатели',
                'verbose_name_plural': 'Индексы и указатели',
                'ordering': ['id'],
            },
        ),
    ]
