# Generated by Django 3.2.10 on 2024-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsprob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='pole3',
            field=models.CharField(default='0', max_length=200, verbose_name='Поле3'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='pole4',
            field=models.CharField(default='0', max_length=200, verbose_name='Поле4'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='res3',
            field=models.IntegerField(default=0, verbose_name='РезЦел3'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='res4',
            field=models.IntegerField(default=0, verbose_name='РезЦел4'),
        ),
    ]
